# Generated by Django 2.2 on 2019-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=20)),
                ('password', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.TextField(max_length=20)),
                ('date', models.IntegerField()),
                ('parent_id', models.IntegerField(null=True)),
                ('tripcode', models.TextField(max_length=150, null=True)),
                ('title', models.TextField(max_length=12)),
                ('name', models.CharField(default='anonymous', max_length=25)),
                ('content', models.TextField(max_length=500000)),
            ],
        ),
    ]
