# Generated by Django 2.2 on 2019-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190609_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_motd',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='site_privacy',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='site_rules',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='site_terms',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
